
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

rooms.page_size = 8

# Mail config
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.username=nguyenvancong72033@gmail.com
mail.password=gsds nkxm lpeb qepo
mail.from=nguyenvancong72033@gmail.com
mail.from.name=SmartHotel
